### ISSUE TITLE
Run django Tests predeploy

### ISSUE THREAD

**Issue by chgad** [mimischi/django-docker#4]
It might be usefull to run project tests, if provided, in the predeploy state and if any of them fails reject the changes. This should only be used for detecting wether there are failing tests or not. So we should keep it simple just, eventually echo the number of failed, and stop the deploy when not passing all tests.

I know that nowadays there are services like Travis CI which do that for you, even Github integrated, but why not double check it ?

**Comment by mimischi** [comment]
I don't think running the unit tests in `pre-deploy` on Dokku is necessary, but you have a point in general. We want to know whether the app is still working after deployment, so we need to have some tests in place.

Dokku provides a `CHECKS` file, where you can define [custom checks](http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/#customizing-checks) (e.g. calling a specific URL and waiting for a response).

**Comment by mimischi** [comment]
After thinking about this some more, I don't think it is necessary to include these pre-deploy checks in this project. It may be sensible for some to do so, but in general we utilize Travis-CI to do any unit testing. If these tests fail, then we just do not push the new versions to production. If all tests pass on Travis-CI, then nothing should go wrong on production.
