### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by chgad** [mimischi/django-docker#5]
Is there a reason why  #3 isn't merged yet ?

**Comment by mimischi** [comment]
Currently it builds both the `local dev` and `production` environments without really testing whether they are working.

I think it would be nice to have some kind of reassurance that things are really up and running. For the `local dev` we call `python manage.py help`, which would fail if at least the database connection wouldn't work.

Further it would be nice to hook up `pytest` for unit tests.
